#+title: Emacs From Scratch Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el


* Welcome!

This is the configuration we've been building in the *Emacs From Scratch* series, now written as an Org Mode document.  This file generates [[file:init.el][init.el]] which can be loaded by Emacs at startup.

# *NOTE:* If you run into any issues while using this configuration, please [[https://github.com/daviwil/emacs-from-scratch/issues/new][file an issue]] or send me an email at =david at systemcrafters.cc=.
The following variables are used to tweak some of the configuration pieces for use in the live streams so you might need to adjust them for your local machine if you try to use this configuration directly.

#+begin_src emacs-lisp

  ;; NOTE: init.el is now generated from Emacs.org.  Please edit that file
  ;;       in Emacs and init.el will be generated automatically!

  ;; You will most likely need to adjust this font size for your system!
  (defvar efs/default-font-size 180)
  (defvar efs/default-variable-font-size 180)

  ;; Make frame transparency overridable
  (defvar efs/frame-transparency '(95 . 90))

#+end_src

#+RESULTS:
: efs/frame-transparency

#+begin_src emacs-lisp
(setq org-roam-v2-ack t)
#+end_src

#+RESULTS:
: t

#+begin_src emacs-lisp
 (defun transparency (value)
   "Sets the transparency of the frame window. 0=transparent/100=opaque"
   (interactive "nTransparency Value 0 - 100 opaque:")
   (set-frame-parameter (selected-frame) 'alpha value))
#+end_src

#+RESULTS:
: transparency

#+begin_src emacs-lisp
  (defun  efs/screen-layout ()
    (interactive)
    ;; NOTE: You will need to update this to a valid background path!
    (start-process-shell-command
     "sh" nil  "sh ~/.screenlayout/default.sh"))
  ;; (efs/screen-layout)
#+end_src

* Tips for Use

In this document I've added links in many places that lead you to documentation for the various packages we use.  If you're looking at this file in Emacs, you can put your cursor on a link and press =C-c C-o= or run =M-x org-open-at-point= to open the link in your web browser.

* Startup Performance

#+begin_src emacs-lisp

  ;; The default is 800 kilobytes.  Measured in bytes.
  (setq gc-cons-threshold (* 50 1000 1000))

  (defun efs/display-startup-time ()
    (message "Emacs loaded in %s with %d garbage collections."
             (format "%.2f seconds"
                     (float-time
                       (time-subtract after-init-time before-init-time)))
             gcs-done))

  (add-hook 'emacs-startup-hook #'efs/display-startup-time)

#+end_src

* Package System Setup

Emacs has a built in package manager but it doesn't make it easy to automatically install packages on a new system the first time you pull down your configuration.  [[https://github.com/jwiegley/use-package][use-package]] is a really helpful package used in this configuration to make it a lot easier to automate the installation and configuration of everything else we use.

#+begin_src emacs-lisp

  ;; Initialize package sources
  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

    ;; Initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)

#+end_src

** Automatic Package Updates

The auto-package-update package helps us keep our Emacs packages up to date!  It will prompt you after a certain number of days either at startup or at a specific time of day to remind you to update your packages.

You can also use =M-x auto-package-update-now= to update right now!

#+begin_src emacs-lisp
  (use-package auto-package-update
    :custom
    (auto-package-update-interval 7)
    (auto-package-update-prompt-before-update t)
    (auto-package-update-hide-results t)
    :config
    (auto-package-update-maybe)
    (auto-package-update-at-time "09:00"))

#+end_src

* Keep Folders Clean

We use the [[https://github.com/emacscollective/no-littering/blob/master/no-littering.el][no-littering]] package to keep folders where we edit files and the Emacs configuration folder clean!  It knows about a wide variety of variables for built in Emacs features as well as those from community packages so it can be much easier than finding and setting these variables yourself.

#+begin_src emacs-lisp

  ;; NOTE: If you want to move everything out of the ~/.emacs.d folder
  ;; reliably, set `user-emacs-directory` before loading no-littering!
  ;(setq user-emacs-directory "~/.cache/emacs")

  (use-package no-littering)

  ;; no-littering doesn't set this by default so we must place
  ;; auto save files in the same path as it uses for sessions
  (setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))

#+end_src

* Basic UI Configuration

This section configures basic UI settings that remove unneeded elements to make Emacs look a lot more minimal and modern.  If you're just getting started in Emacs, the menu bar might be helpful so you can remove the =(menu-bar-mode -1)= line if you'd like to still see that.

#+begin_src emacs-lisp
  (setq inhibit-startup-message t)

  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room

  (menu-bar-mode -1)            ; Disable the menu bar

  ;; Set up the visible bell
  (setq visible-bell t)

  (column-number-mode)
  ;; (global-display-line-numbers-mode t)

  ;; Set frame transparency
  (set-frame-parameter (selected-frame) 'alpha efs/frame-transparency)
  (add-to-list 'default-frame-alist `(alpha . ,efs/frame-transparency))
  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  (add-to-list 'default-frame-alist '(fullscreen . maximized))

  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  ;; treemacs-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

#+RESULTS:

Toggle transparency
#+begin_src emacs-lisp
 (defun toggle-transparency ()
   (interactive)
   (let ((alpha (frame-parameter nil 'alpha)))
     (set-frame-parameter
      nil 'alpha
      (if (eql (cond ((numberp alpha) alpha)
                     ((numberp (cdr alpha)) (cdr alpha))
                     ;; Also handle undocumented (<active> <inactive>) form.
                     ((numberp (cadr alpha)) (cadr alpha)))
               100)
          '(100 . 90) '(95 . 100)))))
 (global-set-key (kbd "C-c t") 'toggle-transparency)
#+end_src

#+RESULTS:
: toggle-transparency

** Font Configuration

I am using the [[https://github.com/tonsky/FiraCode][Fira Code]] and [[https://fonts.google.com/specimen/Cantarell][Cantarell]] fonts for this configuration which will more than likely need to be installed on your machine.  Both can usually be found in the various Linux distro package managers or downloaded from the links above.

#+begin_src emacs-lisp

    (set-face-attribute 'default nil :font "Fira Code Retina" :height efs/default-font-size)

    ;; Set the fixed pitch face
    (set-face-attribute 'fixed-pitch nil :font "Fira Code Retina" :height efs/default-font-size)

    ;; Set the variable pitch face
    (set-face-attribute 'variable-pitch nil :font "Cantarell" :height efs/default-variable-font-size :weight 'regular)


    (defun init-my-font ()
      (set-face-font
       'default
       (font-spec
        :family "Fira Code Retina"
        :height efs/default-font-size
        :slant 'normal))
      (set-face-attribute 'default nil :height 103)
      ;; emoji font
      (set-fontset-font
       t 'symbol
       (font-spec :family "Noto Color Emoji"
                  :height efs/default-variable-font-size
                  :weight 'normal
                  :width 'normal
                  :slant 'normal))
      ;; fallback font
      (set-fontset-font
       t nil
       (font-spec
        :family "DejaVu Sans Mono"
        :height efs/default-font-size
        :slant 'normal)))

#+end_src

#+RESULTS:
: init-my-font

#+begin_src emacs-lisp
    ;; "CCSymbol"  U+1F16D - U+1F10F
    (set-fontset-font "fontset-default"
                      (cons (decode-char 'ucs #x1F10D)
                            (decode-char 'ucs #x1F10f))
                      "CC Symbols")
  
      (set-fontset-font "fontset-default"
                      (cons (decode-char 'ucs #x1F16D)
                            (decode-char 'ucs #x1F16f))
                      "CC Symbols")
       ;; (set-fontset-font "fontset-default"
       ;;                   (cons (decode-char 'ucs #x05D0))
       ;;                   "Noto Serif Hebew")
#+end_src

#+RESULTS:

#+begin_src emacs-lisp
  (set-fontset-font "fontset-default"
                    (cons (decode-char 'ucs #x05B0)
                          (decode-char 'ucs #x05F4))
                    "Noto Serif Hebrew")
  
#+end_src

** Emojis and Ligatures
#+begin_src emacs-lisp
  (use-package unicode-fonts
     :ensure t
     :config
      (unicode-fonts-setup))
#+end_src
#+RESULTS:
: t


** Emojify
#+begin_src emacs-lisp
(use-package emojify
  :hook (after-init . global-emojify-mode))
#+end_src

#+RESULTS:
| rainbow-delimiters-mode | global-emojify-mode | x-wm-set-size-hint | tramp-register-archive-file-name-handler | magit-maybe-define-global-key-bindings |

#+begin_src emacs-lisp
  (setq emojify-user-emojis '((":emacs:" . (("name" . "Emacs")
                                                ("image" . "~/.emacs.d/emoji/emacs.svg")
                                                ("style" . "github")))
                              (":lambda:" . (("name" . "Lambda")
                                                ("image" . "~/.emacs.d/emoji/lambda.jpg")
                                                ("style" . "github")))))
  ;; If emojify is already loaded refresh emoji data
  (when (featurep 'emojify)
    (emojify-set-emoji-data))
#+end_src

#+RESULTS:
** Pretty-symbols
#+begin_src emacs-lisp
  (use-package fira-code-mode
    :custom (fira-code-mode-disabled-ligatures '("[]" "#{" "#(" "#_" "#_(" "x" "*" "**" "***" ":" "::" "www" "->" "->>" "+"))
    :hook (
           (prog-mode . prettify-symbols-mode)
           (prog-mode . fira-code-mode)
           (special-mode . prettify-symbols-mode)
           (special-mode . fira-code-mode)
           (text-mode . prettify-symbols-mode)
           ))
  #+end_src

#+RESULTS:
| prettify-symbols-mode | rainbow-delimiters-mode | nyan-mode | text-mode-hook-identify |
** Nyan Cat Mode
#+begin_src emacs-lisp
  ;; (use-package nyan-mode
  ;;   :hook ((special-mode . nyan-mode)
  ;;          (text-mode . nyan-mode)
  ;;          (progn-mode . nyan-mode)))
#+end_src
** Rain 

* Keybinding Configuration

This configuration uses [[https://evil.readthedocs.io/en/latest/index.html][evil-mode]] for a Vi-like modal editing experience.  [[https://github.com/noctuid/general.el][general.el]] is used for easy keybinding configuration that integrates well with which-key.  [[https://github.com/emacs-evil/evil-collection][evil-collection]] is used to automatically configure various Emacs modes with Vi-like keybindings for evil-mode.

#+begin_src emacs-lisp
  ;; Make ESC quit prompts
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

  (use-package general
    :after evil
    :config
    (general-create-definer efs/leader-keys
      :keymaps '(normal insert visual emacs)
      :prefix "SPC"
      :global-prefix "C-SPC")

    (efs/leader-keys
      "t"  '(:ignore t :which-key "toggles")
      "tt" '(counsel-load-theme :which-key "choose theme")
      "fde" '(lambda () (interactive) (find-file (expand-file-name "~/.emacs.default/Emacs.org")) :which-key "Emacs config")
      "k" '(lambda () (interactive) (org-babel-previous-src-block) :which-key "Previous block")
      "j" '(lambda () (interactive) (org-babel-next-src-block) :which-key "Next block")
      "ph" '(lambda () (interactive) (find-file (expand-file-name "~/Projects/Habits.org")) :which-key "Habits")
      "pi" '(lambda () (interactive) (find-file (expand-file-name "~/Projects/IMPA.org")) :which-key "IMPA")
      "pps" '(lambda () (interactive) (find-file (expand-file-name "~/Projects/ProcSel.org")) :which-key "Processo Seletivo")
      "ppp" '(lambda () (interactive) (find-file (expand-file-name "~/Projects/Programming.org")) :which-key "Programming")
      "pr" '(lambda () (interactive) (find-file (expand-file-name "~/Projects/Research.org")) :which-key "Reasearch")
      "pt" '(lambda () (interactive) (find-file (expand-file-name "~/Projects/Tasks.org")))
      "pu" '(lambda () (interactive) (find-file (expand-file-name "~/Projects/University.org")))))

  (use-package evil
    :init
    (setq evil-want-keybinding nil)
    (setq evil-want-integration t)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))

  (use-package evil-collection
    :after evil
    :init
    (setq evil-want-keybinding nil)
    :config
    (evil-collection-init))

  ;;   (use-package general
  ;;   :config
  ;;   (general-evil-setup t)

  ;;   (general-create-definer dw/leader-key-def
  ;;     :keymaps '(normal insert visual emacs)
  ;;     :prefix "SPC"
  ;;     :global-prefix "C-SPC")

  ;;   (general-create-definer dw/ctrl-c-keys
  ;;     :prefix "C-c"))

#+end_src

#+RESULTS:
: t

* UI Configuration
** Command Log Mode

[[https://github.com/lewang/command-log-mode][command-log-mode]] is useful for displaying a panel showing each key binding you use in a panel on the right side of the frame.  Great for live streams and screencasts!

#+begin_src emacs-lisp

  (use-package command-log-mode
    :commands command-log-mode)

#+end_src

** Color Theme

[[https://github.com/hlissner/emacs-doom-themes][doom-themes]] is a great set of themes with a lot of variety and support for many different Emacs modes.  Taking a look at the [[https://github.com/hlissner/emacs-doom-themes/tree/screenshots][screenshots]] might help you decide which one you like best.  You can also run =M-x counsel-load-theme= to choose between them easily.
# <
#+begin_src emacs-lisp
  (use-package doom-themes
    :init (load-theme 'doom-Iosvkem t)) ;;wildavil's default -> doom-palenight
#+end_src

#+RESULTS:

** Better Modeline

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a very attractive and rich (yet still minimal) mode line configuration for Emacs.  The default configuration is quite good but you can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run `M-x all-the-icons-install-fonts` so that mode line icons display correctly.

#+begin_src emacs-lisp

  (use-package all-the-icons)

  (use-package doom-modeline
    :init (doom-modeline-mode 1)
    :custom ((doom-modeline-height 10))
    :config
    (setq doom-modeline-buffer-file-name-style 'truncate-with-project)
    (setq doom-modeline--batery-status t)
    (setq doom-modeline-lsp t)
    (display-battery-mode 1))
#+end_src

#+RESULTS:
: t

** Which Key

[[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.

#+begin_src emacs-lisp

  (use-package which-key
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 1))

#+end_src

** Ivy and Counsel

[[https://oremacs.com/swiper/][Ivy]] is an excellent completion framework for Emacs.  It provides a minimal yet powerful selection menu that appears when you open files, switch buffers, and for many other tasks in Emacs.  Counsel is a customized set of commands to replace `find-file` with `counsel-find-file`, etc which provide useful commands for each of the default completion commands.

[[https://github.com/Yevgnen/ivy-rich][ivy-rich]] adds extra columns to a few of the Counsel commands to provide more information about each item.

#+begin_src emacs-lisp

  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-alt-done)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))

  (use-package ivy-rich
    :after ivy
    :init
    (ivy-rich-mode 1))

  (use-package counsel
    :bind (("C-M-j" . 'counsel-switch-buffer)
           ("C-c r" . 'revert-buffer)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :custom
    (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
    :config
    (counsel-mode 1))

#+end_src

#+RESULTS:
: counsel-minibuffer-history

*** Improved Candidate Sorting with prescient.el

prescient.el provides some helpful behavior for sorting Ivy completion candidates based on how recently or frequently you select them.  This can be especially helpful when using =M-x= to run commands that you don't have bound to a key but still need to access occasionally.

This Prescient configuration is optimized for use in System Crafters videos and streams, check out the [[https://youtu.be/T9kygXveEz0][video on prescient.el]] for more details on how to configure it!

#+begin_src emacs-lisp

  (use-package ivy-prescient
    :after counsel
    :custom
    (ivy-prescient-enable-filtering nil)
    :config
    ;; Uncomment the following line to have sorting remembered across sessions!
    (prescient-persist-mode 1)
    (ivy-prescient-mode 1))

#+end_src

#+RESULTS:
: t

** Helpful Help Commands

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp

  (use-package helpful
    :commands (helpful-callable helpful-variable helpful-command helpful-key)
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))

#+end_src

** Text Scaling

This is an example of using [[https://github.com/abo-abo/hydra][Hydra]] to design a transient key binding for quickly adjusting the scale of the text on screen.  We define a hydra that is bound to =C-s t s= and, once activated, =j= and =k= increase and decrease the text scale.  You can press any other key (or =f= specifically) to exit the transient key map.

#+begin_src emacs-lisp
  (use-package hydra
    :defer t)

  (defhydra hydra-text-scale (:timeout 4)
    "scale text"
    ("j" text-scale-increase "in")
    ("k" text-scale-decrease "out")
    ("f" nil "finished" :exit t))

  (efs/leader-keys
    "ts" '(hydra-text-scale/body :which-key "scale text"))
#+end_src

** PDF-tools
#+begin_src emacs-lisp
  (use-package pdf-tools
    :config
    (pdf-loader-install))
#+end_src

#+RESULTS:
: t

* Languages
** Julia

*** Major mode

#+begin_src emacs-lisp
(use-package julia-mode)
#+end_src

#+RESULTS:

#+begin_src emacs-lisp
(use-package julia-snail)
#+end_src

#+RESULTS:

#+begin_src emacs-lisp
   (setq inferior-julia-program-name "julia")
#+end_src

#+RESULTS:
: julia

#+begin_src emacs-lisp
  (package-install-file "~/.emacs.default/ob-julia-vterm.el/ob-julia-vterm.el")  
#+end_src

#+RESULTS:
: #s(package-desc ob-julia-vterm (0 2) "Babel Functions for Julia in VTerm" ((emacs (26 1)) (julia-vterm (0 10))) single nil nil ((:authors ("Shigeaki Nishina")) (:maintainer "Shigeaki Nishina") (:keywords "julia" "org" "outlines" "literate programming" "reproducible research") (:url . "https://github.com/shg/ob-julia-vterm.el")) nil)

#+begin_src emacs-lisp
(defalias 'org-babel-execute:julia 'org-babel-execute:julia-vterm)
#+end_src

#+RESULTS:
: org-babel-execute:julia
** Clojure

*** Major mode (code formatter included)
#+begin_src emacs-lisp
  (use-package clojure-mode
    :hook ((clojure-mode . subword-mode)
           (clojure-mode . paredit-mode)
           (clojure-mode . smartparens-strict-mode)
           (clojure-mode . aggressive-indent-mode)))
  ;; :hook ((paredit-mode . clojure-mode))
#+end_src

#+RESULTS:
: t

#+begin_src emacs-lisp
(setq clojure-align-forms-automatically t)
#+end_src

#+RESULTS:
: t

*** Extra font-locking
#+begin_src emacs-lisp
(use-package clojure-mode-extra-font-locking)
#+end_src

#+RESULTS:

*** Lint tools
#+begin_src emacs-lisp
  (use-package kibit-helper)
#+end_src

#+RESULTS:

#+begin_src emacs-lisp
  (use-package anakondo)
  (use-package flymake-kondor)
  (use-package flycheck-clj-kondo)
#+end_src

#+RESULTS:

* Org Mode
[[https://orgmode.org/][Org Mode]] is one of the hallmark features of Emacs.  It is a rich document editor, project planner, task and time tracker, blogging engine, and literate coding utility all wrapped up in one package.

** Better Font Faces

The =efs/org-font-setup= function configures various text faces to tweak the sizes of headings and use variable width fonts in most cases so that it looks more like we're editing a document in =org-mode=.  We switch back to fixed width (monospace) fonts for code blocks and tables so that they display correctly.

#+begin_src emacs-lisp

  (defun efs/org-font-setup ()
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

    ;; ;; Set faces for heading levels
    ;; (dolist (face '((org-level-1 . 1.2)
    ;;                 (org-level-2 . 1.1)
    ;;                 (org-level-3 . 1.05)
    ;;                 (org-level-4 . 1.0)
    ;;                 (org-level-5 . 1.1)
    ;;                 (org-level-6 . 1.1)
    ;;                 (org-level-7 . 1.1)
    ;;                 (org-level-8 . 1.1)))
    ;;   (set-face-attribute (car face) nil :font "Cantarell" :weight 'regular :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil    :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil    :inherit 'fixed-pitch)
    (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil     :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil    :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil  :inherit 'fixed-pitch)
    (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
    (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch)
    ;; (set-face-attribute 'org-format-latex-options nil :inherit 'fixed-pitch)
    ;; ;
    (setq org-format-latex-options (plist-put org-format-latex-options :scale 3.0)))

#+end_src

#+RESULTS:
: efs/org-font-setup
 

** Org-auto-tangle
   #+begin_src emacs-lisp
(use-package org-auto-tangle
  :load-path "site-lisp/org-auto-tangle/"    ;; this line is necessary only if you cloned the repo in your site-lisp directory 
  :defer t
  :hook (org-mode . org-auto-tangle-mode))
   #+end_src

   #+RESULTS:

** Basic Config

*** Setup
This section contains the basic configuration for =org-mode= plus the configuration for Org agendas and capture templates.  There's a lot to unpack in here so I'd recommend watching the videos for [[https://youtu.be/VcgjTEa0kU4][Part 5]] and [[https://youtu.be/PNE-mgkZ6HM][Part 6]] for a full explanation.

#+begin_src emacs-lisp
  (defun efs/org-mode-setup ()
    (org-indent-mode)
    (variable-pitch-mode 1)
    (visual-line-mode 1))

  ;; (defun bw/org-motion-setup ()
  ;;   (general-create-definer bw/org-leader-keys
  ;;     :keymaps '(normal visual emacs)
  ;;     :prefix "SPC")
  ;;   (bw/org-leader-keys
  ;;    "j" '(lambdaorg-babel-next-src-block)
  ;;    "k" '(org-babel-previous-src-block)
  ;;    "SPC" '(org-ctrl-c-ctrl-c)))

  (use-package org
    :pin org
    :commands (org-capture org-agenda)
    :hook ((org-mode . efs/org-mode-setup)
           ;; (org-mode . bw/org-motion-setup)
           (org-mode . auto-fill-mode))
    :config
    (setq org-ellipsis " ▾")

    (setq org-agenda-start-with-log-mode t)
    (setq org-log-done 'time)
    (setq org-log-into-drawer t)

    (setq org-agenda-files
          '("~/Projects/Tasks.org"
            "~/Projects/Habits.org"
            "~/Projects/IMPA.org"
            "~/Projects/ProcSel.org"
            "~/Projects/University.org"
            "~/Projects/Research.org"))

    (require 'org-habit)
    (add-to-list 'org-modules 'org-habit)
    (setq org-habit-graph-column 60)

    (setq org-todo-keywords
          '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
            (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

    (setq org-refile-targets
          '(("Archive.org" :maxlevel . 1)
            ("Tasks.org" :maxlevel . 1)))

    ;; Save Org buffers after refiling!
    (advice-add 'org-refile :after 'org-save-all-org-buffers)

    (setq org-tag-alist
          '((:startgroup)
                                          ; Put mutually exclusive tags here
            (:endgroup)
            ("@errand" . ?E)
            ("@home" . ?H)
            ("@work" . ?W)
            ("agenda" . ?a)
            ("planning" . ?p)
            ("publish" . ?P)
            ("batch" . ?b)
            ("note" . ?n)
            ("idea" . ?i)))

    ;; Configure custom agenda views
    (setq org-agenda-custom-commands
          '(("d" "Dashboard"
             ((agenda "" ((org-deadline-warning-days 7)))
              (todo "NEXT"
                    ((org-agenda-overriding-header "Next Tasks")))
              (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

            ("n" "Next Tasks"
             ((todo "NEXT"
                    ((org-agenda-overriding-header "Next Tasks")))))

            ("W" "Work Tasks" tags-todo "+work-email")

            ;; Low-effort next actions
            ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
             ((org-agenda-overriding-header "Low Effort Tasks")
              (org-agenda-max-todos 20)
              (org-agenda-files org-agenda-files)))

            ("w" "Workflow Status"
             ((todo "WAIT"
                    ((org-agenda-overriding-header "Waiting on External")
                     (org-agenda-files org-agenda-files)))
              (todo "REVIEW"
                    ((org-agenda-overriding-header "In Review")
                     (org-agenda-files org-agenda-files)))
              (todo "PLAN"
                    ((org-agenda-overriding-header "In Planning")
                     (org-agenda-todo-list-sublevels nil)
                     (org-agenda-files org-agenda-files)))
              (todo "BACKLOG"
                    ((org-agenda-overriding-header "Project Backlog")
                     (org-agenda-todo-list-sublevels nil)
                     (org-agenda-files org-agenda-files)))
              (todo "READY"
                    ((org-agenda-overriding-header "Ready for Work")
                     (org-agenda-files org-agenda-files)))
              (todo "ACTIVE"
                    ((org-agenda-overriding-header "Active Projects")
                     (org-agenda-files org-agenda-files)))
              (todo "COMPLETED"
                    ((org-agenda-overriding-header "Completed Projects")
                     (org-agenda-files org-agenda-files)))
              (todo "CANC"
                    ((org-agenda-overriding-header "Cancelled Projects")
                     (org-agenda-files org-agenda-files)))))))

    (setq org-capture-templates
          `(("t" "Tasks / Projects")
            ("tt" "Task" entry (file+olp "~/Projects/Code/emacs-from-scratch/OrgFiles/Tasks.org" "Inbox")
             "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

            ("j" "Journal Entries")
            ("jj" "Journal" entry
             (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
             "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
             ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
             :clock-in :clock-resume
             :empty-lines 1)
            ("jm" "Meeting" entry
             (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
             "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
             :clock-in :clock-resume
             :empty-lines 1)

            ("w" "Workflows")
            ("we" "Checking Email" entry (file+olp+datetree "~/Projects/Code/emacs-from-scratch/OrgFiles/Journal.org")
             "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)

            ("m" "Metrics Capture")
            ("mw" "Weight" table-line (file+headline "~/Projects/Code/emacs-from-scratch/OrgFiles/Metrics.org" "Weight")
             "| %U | %^{Weight} | %^{Notes} |" :kill-buffer t)))

    (define-key global-map (kbd "C-c j")
      (lambda () (interactive) (org-capture nil "jj")))

    (efs/org-font-setup))
#+end_src

#+RESULTS:
| bw/org-motion-setup | org-evil--org-mode-hook-fn | org-ref-org-menu | (lambda nil (add-hook 'after-save-hook #'efs/org-babel-tangle-config)) | org-tempo-setup | org-display-inline-images | efs/org-mode-visual-fill | (lambda nil (org-bullets-mode 1)) | org-superstar-mode | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-show-all append local] 5] | auto-fill-mode | efs/org-mode-setup | org-auto-tangle-mode | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | #[0 \301\211\207 [imenu-create-index-function org-imenu-get-tree] 2] | (lambda nil (display-line-numbers-mode 0)) |

*** Nicer Heading Bullets 

[[https://github.com/sabof/org-bullets][org-bullets]] replaces the heading stars in =org-mode= buffers with nicer looking characters that you can control.  Another option for this is [[https://github.com/integral-dw/org-superstar-mode][org-superstar-mode]] which we may cover in a later video.

#+begin_src emacs-lisp  
  (use-package org-bullets
    :after org
    ;; :hook (org-mode . org-bullets)
    :custom
    ;; (org-superstar-remove-leading-stars t)
    (org-bullets-bullet-list '("家" "ॐ" "同" "Ø" "א" "҉ " "҈ ")))
  ;; ("֍" "ॐ" "፠" "Ø" "א" "҉" "҈")
#+end_src

#+RESULTS:


#+begin_src emacs-lisp
  (use-package org-superstar
    ;; :if (not dw/is-termux)
    :after org
    :hook (org-mode . org-superstar-mode)
    :custom
    (org-superstar-remove-leading-stars t)
    (org-superstar-headline-bullets-list '("家" "ॐ" "同" "Ø" "א" "҉ " "҈ ")))
  ;; ("◉" "○" "●" "○" "●" "○" "●")
  ;; Replace list hyphen with dot
  ;; (font-lock-add-keywords 'org-mode
  ;;                         '(("^ *\\([-]\\) "
  ;;                             (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

  ;; Increase the size of various headings
  ;; (set-face-attribute 'org-document-title nil :font "Cantarell" :weight 'bold :height 1.3)
  ;; (dolist (face '((org-level-1 . 1.2)
  ;;                 (org-level-2 . 1.1)
  ;;                 (org-level-3 . 1.05)
  ;;                 (org-level-4 . 1.0)
  ;;                 (org-level-5 . 1.1)
  ;;                 (org-level-6 . 1.1)
  ;;                 (org-level-7 . 1.1)
  ;;                 (org-level-8 . 1.1)))
  ;;   (set-face-attribute (car face) nil :font "Cantarell" :weight 'medium :height (cdr face)))

  ;; Make sure org-indent face is available
  (require 'org-indent)

  ;; Ensure that anything that should be fixed-pitch in Org files appears that way
  (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
  (set-face-attribute 'org-table nil  :inherit 'fixed-pitch)
  (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
  (set-face-attribute 'org-code nil   :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-indent nil :inherit '(org-hide fixed-pitch))
  (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)

  ;; Get rid of the background on column views
  (set-face-attribute 'org-column nil :background nil)
  (set-face-attribute 'org-column-title nil :background nil)

  ;; TODO: Others to consider
  ;; '(org-document-info-keyword ((t (:inherit (shadow fixed-pitch)))))
  ;; '(org-meta-line ((t (:inherit (font-lock-comment-face fixed-pitch)))))
  ;; '(org-property-value ((t (:inherit fixed-pitch))) t)
  ;; '(org-special-keyword ((t (:inherit (font-lock-comment-face fixed-pitch)))))
  ;; '(org-table ((t (:inherit fixed-pitch :foreground "#83a598"))))
  ;; '(org-tag ((t (:inherit (shadow fixed-pitch) :weight bold :height 0.8))))
  ;; '(org-verbatim ((t (:inherit (shadow fixed-pitch))))))
#+end_src

#+RESULTS:


#+begin_src emacs-lisp
  (require 'org-bullets)
  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
#+end_src


# #+begin_src emacs-lisp  
#     (use-package org-superstar
#     ;; :if (not dw/is-termux)
#     :after org
#     :hook (org-mode . org-superstar-mode)
#     :custom
#     (org-superstar-remove-leading-stars t)
#     (org-superstar-headline-bullets-list '("֍" "ॐ" "፠" "Ø" "א" "҉" "҈")))  
# #+end_src

 #+RESULTS:

*** Some (font) configs
    #+begin_src emacs-lisp
	;; Increase the size of various headings
     ;; Noto Serif CJK TC
      (set-face-attribute 'org-document-title nil :font "Bitstream Vera Serif" :weight 'bold :height 1.3)
      (dolist (face '((org-level-1 . 1.2)
		      (org-level-2 . 1.1)
		      (org-level-3 . 1.05)
		      (org-level-4 . 1.0)
		      (org-level-5 . 1.1)
		      (org-level-6 . 1.1)
		      (org-level-7 . 1.1)
		      (org-level-8 . 1.1)))
	(set-face-attribute (car face) nil :font "Bitstream Vera Serif" :weight 'medium :height (cdr face)))
      
      ;; Make sure org-indent face is available
      (require 'org-indent)
      
      ;; Ensure that anything that should be fixed-pitch in Org files appears that way
      (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
      (set-face-attribute 'org-table nil  :inherit 'fixed-pitch)
      (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
      (set-face-attribute 'org-code nil   :inherit '(shadow fixed-pitch))
      (set-face-attribute 'org-indent nil :inherit '(org-hide fixed-pitch))
      (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
      (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
      (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
      (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)
      
      ;; Get rid of the background on column views
      (set-face-attribute 'org-column nil :background nil)
      (set-face-attribute 'org-column-title nil :background nil)
    #+end_src

    #+RESULTS:

*** Center Org Buffers

We use [[https://github.com/joostkremers/visual-fill-column][visual-fill-column]] to center =org-mode= buffers for a more pleasing writing experience as it centers the contents of the buffer horizontally to seem more like you are editing a document.  This is really a matter of personal preference so you can remove the block below if you don't like the behavior.

#+begin_src emacs-lisp
  (defun efs/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
	  visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . efs/org-mode-visual-fill))
#+end_src

#+RESULTS:
| org-evil--org-mode-hook-fn | org-ref-org-menu | (lambda nil (add-hook 'after-save-hook #'efs/org-babel-tangle-config)) | org-tempo-setup | org-display-inline-images | efs/org-mode-visual-fill | (lambda nil (org-bullets-mode 1)) | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-show-all append local] 5] | #[0 \300\301\302\303\304$\207 [add-hook change-major-mode-hook org-babel-show-result-all append local] 5] | org-babel-result-hide-spec | org-babel-hide-all-hashes | #[0 \301\211\207 [imenu-create-index-function org-imenu-get-tree] 2] | efs/org-mode-setup | org-auto-tangle-mode | (lambda nil (display-line-numbers-mode 0)) | org-ref-setup-label-finders |

# *** Inline Images
# #+begin_src emacs-lisp
#   ;; -- Display images in org mode
#   ;; enable image mode first
#   (use-package iimage-mode
#     ;; add the org file link format to the iimage mode regex
#     :init
#     (add-to-list & 'iimage-mode-image-regex-alist
#                  (cons (concat "\\[\\[file:\\(~?" iimage-mode-image-filename-regex "\\)\\]") ))
#     ;;  add a hook so we can display images on load
#     (add-hook & 'org-mode-hook & '(lambda () (org-turn-on-iimage-in-org)))
#     ;; function to setup images for display on load
#     (defun org-turn-on-iimage-in-org ()
#       "display images in your org file"
#       (interactive)
#       (turn-on-iimage-mode)
#       (set-face-underline-p & 'org-link nil))
#     ;; function to toggle images in a org bugger
#     (defun org-toggle-iimage-in-org ()
#       "display images in your org file"
#       (interactive)
#       (if (face-underline-p & 'org-link)
#           (set-face-underline-p & 'org-link nil)
#         (set-face-underline-p & 'org-link t))
#       (call-interactively & 'iimage-mode)))

#   (define-key org-mode-map (kbd "C-S-a") & 'org-archive-subtree)
#   #+end_src

#+RESULTS:

Chosing an image's size with :width property
#+begin_example
#+ATTR_ORG: :width 100
#+end_example

#+begin_src emacs-lisp
  (setq org-image-actual-width nil)
#+end_src

#+RESULTS:

*** Specific 

** Configure Babel Languages

#+begin_src emacs-lisp
(use-package ein)
#+end_src

#+RESULTS:

#+begin_src emacs-lisp
  (add-hook 'org-babel-after-execute-hook 'org-display-inline-images)   
  (add-hook 'org-mode-hook 'org-display-inline-images)
#+end_src

#+begin_src emacs-lisp
  ;; (use-package ob-julia)
#+end_src

 - Ob-julia unofficial

#+begin_src emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/ob-julia")
#+end_src

To execute or export code in =org-mode= code blocks, you'll need to set up =org-babel-load-languages= for each language you'd like to use.  [[https://orgmode.org/worg/org-contrib/babel/languages.html][This page]] documents all of the languages that you can use with =org-babel=.

#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t)
       (python . t)
       (browser . t)
       (ditaa . t)
       (R . t)
       (go . t) 
       ;; (ipython . t)
       (julia-vterm . t)
       ;; (julia . t)
       (ein . t)
       (ditaa . t)
       (css . t)
       (lisp . t)
       (latex . t)
       (clojure . t)
       (clojurescript . t)))

    (push '("conf-unix" . conf-unix) org-src-lang-modes))
#+end_src

#+RESULTS:
: ((conf-unix . conf-unix) (dot . graphviz-dot) (conf-unix . conf-unix) (ein-julia . julia) (ein-r . R) (ein-R . R) (ein-python . python) (ein . python) (julia-vterm . julia) (browser . html) (C . c) (C++ . c++) (asymptote . asy) (bash . sh) (beamer . latex) (calc . fundamental) (cpp . c++) (ditaa . artist) (dot . fundamental) (elisp . emacs-lisp) (ocaml . tuareg) (screen . shell-script) (shell . sh) (sqlite . sql))

#+begin_src emacs-lisp
  (custom-set-variables
   '(ob-ein-languages
    '(("ein-python" . python)
      ("ein-R" . R)
      ("ein-r" . R)
      ("ein-julia" . julia))))
#+end_src

#+RESULTS:

*** Clojure(script)
#+begin_src emacs-lisp
  (require 'ob-clojure)
  (setq org-babel-clojure-backend 'cider)
#+end_src

** Structure Templates

Org Mode's [[https://orgmode.org/manual/Structure-Templates.html][structure templates]] feature enables you to quickly insert code blocks into your Org files in combination with =org-tempo= by typing =<= followed by the template name like =el= or =py= and then press =TAB=.  For example, to insert an empty =emacs-lisp= block below, you can type =<el= and press =TAB= to expand into such a block.

You can add more =src= block templates below by copying one of the lines and changing the two strings at the end, the first to be the template name and the second to contain the name of the language [[https://orgmode.org/worg/org-contrib/babel/languages.html][as it is known by Org Babel]].

#+begin_src emacs-lisp
  (require 'org-tempo)

  ;; System
  (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))

  ;; Scientific
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("ju" . "src julia"))
  (add-to-list 'org-structure-template-alist '("cl" . "src clojure"))

  ;; Web
  (add-to-list 'org-structure-template-alist '("c4" . "src css :tangle ../css/.css :mkdirp yes"))
  (add-to-list 'org-structure-template-alist '("js" . "src js :tangle ../js/.js"))
  (add-to-list 'org-structure-template-alist '("h4" . "src html :tangle ../html/index.html :mkdirp yes"))

#+end_src

** Auto-tangle Configuration Files

This snippet adds a hook to =org-mode= buffers so that =efs/org-babel-tangle-config= gets executed each time such a buffer gets saved.  This function checks to see if the file being saved is the Emacs.org file you're looking at right now, and if so, automatically exports the configuration here to the associated output files.

#+begin_src emacs-lisp

  ;; Automatically tangle our Emacs.org config file when we save it
  (defun efs/org-babel-tangle-config ()
    (when (string-equal (file-name-directory (buffer-file-name))
                        (expand-file-name user-emacs-directory))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'efs/org-babel-tangle-config)))

#+end_src

** Presentations
   #+begin_src emacs-lisp
     (defun dw/org-present-prepare-slide ()
       (org-overview)
       (org-show-entry)
       (org-show-children))

     (defun dw/org-present-hook ()
       (setq-local face-remapping-alist '((default (:height 1.5) variable-pitch)
					  (header-line (:height 4.5) variable-pitch)
					  (org-document-title (:height 1.75) org-document-title)
					  (org-code (:height 1.55) org-code)
					  (org-verbatim (:height 1.55) org-verbatim)
					  (org-block (:height 1.25) org-block)
					  (org-block-begin-line (:height 0.7) org-block)))
       (setq header-line-format " ")
       (org-appear-mode -1)
       (org-display-inline-images)
       (dw/org-present-prepare-slide))

     (defun dw/org-present-quit-hook ()
       (setq-local face-remapping-alist '((default variable-pitch default)))
       (setq header-line-format nil)
       (org-present-small)
       (org-remove-inline-images)
       (org-appear-mode 1))

     (defun dw/org-present-prev ()
       (interactive)
       (org-present-prev)
       (dw/org-present-prepare-slide))

     (defun dw/org-present-next ()
       (interactive)
       (org-present-next)
       (dw/org-present-prepare-slide))

     (use-package org-present
       :bind (:map org-present-mode-keymap
		   ("C-c C-j" . dw/org-present-next)
		   ("C-c C-k" . dw/org-present-prev))
       :hook ((org-present-mode . dw/org-present-hook)
	      (org-present-mode-quit . dw/org-present-quit-hook)))
   #+end_src

   #+RESULTS:
   : dw/org-present-prev

** Org-download
#+begin_src emacs-lisp
(use-package org-download)
#+end_src

#+RESULTS:

** Org-roam and Bibtex
It's a requirement for org-roam-bibtex,  org-roam, org-ref and bibtex-completion.
#+begin_src emacs-lisp
(use-package org-auto-tangle)
#+end_src

#+RESULTS:

 #+begin_src emacs-lisp
   (use-package org-roam
     :ensure t
     :custom
     (org-roam-directory "~/buddhi-roam")
     :bind (("C-c n l" . org-roam-buffer-toggle)
            ("C-c n f" . org-roam-node-find)
            ("C-c n g" . org-roam-graph)
            ("C-c n i" . org-roam-node-insert))
     :config
     (org-roam-db-autosyc-mode)
     (require 'org-roam-protocol))

   (use-package graphviz-dot-mode
     :ensure t)
 #+end_src

#+RESULTS:

#+begin_src emacs-lisp
(use-package org-ref)
#+end_src

#+RESULTS:

#+begin_src emacs-lisp
  (use-package bibtex-utils)
  (use-package company-bibtex)
  (use-package gscholar-bibtex)
#+end_src

#+RESULTS:

#+begin_src emacs-lisp
(use-package helm-bibtex)
#+end_src

#+RESULTS:

#+begin_src emacs-lisp
(use-package org-roam-bibtex)
#+end_src

#+RESULTS:

** Gantt charts

*** Dependencies
#+begin_src emacs-lisp
  ;; (use-package org-ql)
#+end_src

#+begin_src emacs-lisp
(use-package ts)
#+end_src

#+begin_src emacs-lisp
(use-package s)
#+end_src

#+begin_src emacs-lisp
(use-package dash)
#+end_src

*** Install
As it is hand-maiden: https://github.com/legalnonsense/elgantt/,

#+begin_src shell
  # cd ~/.emacs.d/lisp
  # git clone https://github.com/legalnonsense/elgantt.git
#+end_src

#+begin_src emacs-lisp
  ;; (add-to-list 'load-path (concat user-emacs-directory "lisp/elgantt/test.orgmode")) ;; Or wherever it is located
  ;; (require 'elgantt)
  ;; ;; (setq elgantt-agenda-files (concat user-emacs-directory "lisp/elgantt/test.org"))
#+end_src

#+RESULTS:
: ~/.emacs.d/lisp/elgantt/test.org

** Anaconda
   #+begin_src emacs-lisp
     (use-package conda
       :config
       (setq
        conda-env-home-directory (expand-file-name "~/.conda/")
        conda-env-subdirectory "envs")
       (custom-set-variables '(conda-anaconda-home "/opt/anaconda2/"))
       (conda-env-initialize-interactive-shells)
       (conda-env-initialize-eshell)
       (conda-env-autoactivate-mode t))
   #+end_src

   #+RESULTS:
   : t
 
* Terminals
** term-mode

=term-mode= is a built-in terminal emulator in Emacs.  Because it is written in Emacs Lisp, you can start using it immediately with very little configuration.  If you are on Linux or macOS, =term-mode= is a great choice to get started because it supports fairly complex terminal applications (=htop=, =vim=, etc) and works pretty reliably.  However, because it is written in Emacs Lisp, it can be slower than other options like =vterm=.  The speed will only be an issue if you regularly run console apps with a lot of output.

One important thing to understand is =line-mode= versus =char-mode=.  =line-mode= enables you to use normal Emacs keybindings while moving around in the terminal buffer while =char-mode= sends most of your keypresses to the underlying terminal.  While using =term-mode=, you will want to be in =char-mode= for any terminal applications that have their own keybindings.  If you're just in your usual shell, =line-mode= is sufficient and feels more integrated with Emacs.

With =evil-collection= installed, you will automatically switch to =char-mode= when you enter Evil's insert mode (press =i=).  You will automatically be switched back to =line-mode= when you enter Evil's normal mode (press =ESC=).

Run a terminal with =M-x term!=

*Useful key bindings:*

- =C-c C-p= / =C-c C-n= - go back and forward in the buffer's prompts (also =[[= and =]]= with evil-mode)
- =C-c C-k= - Enter char-mode
- =C-c C-j= - Return to line-mode
- If you have =evil-collection= installed, =term-mode= will enter char mode when you use Evil's Insert mode

#+begin_src emacs-lisp

  (use-package term
    :commands term
    :config
    (setq explicit-shell-file-name "bash") ;; Change this to zsh, etc
    ;;(setq explicit-zsh-args '())         ;; Use 'explicit-<shell>-args for shell-specific args

    ;; Match the default Bash shell prompt.  Update this if you have a custom prompt
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *"))

#+end_src

*** Better term-mode colors

The =eterm-256color= package enhances the output of =term-mode= to enable handling of a wider range of color codes so that many popular terminal applications look as you would expect them to.  Keep in mind that this package requires =ncurses= to be installed on your machine so that it has access to the =tic= program.  Most Linux distributions come with this program installed already so you may not have to do anything extra to use it.

#+begin_src emacs-lisp

  (use-package eterm-256color
    :hook (term-mode . eterm-256color-mode))

#+end_src

** vterm

[[https://github.com/akermu/emacs-libvterm/][vterm]] is an improved terminal emulator package which uses a compiled native module to interact with the underlying terminal applications.  This enables it to be much faster than =term-mode= and to also provide a more complete terminal emulation experience.

Make sure that you have the [[https://github.com/akermu/emacs-libvterm/#requirements][necessary dependencies]] installed before trying to use =vterm= because there is a module that will need to be compiled before you can use it successfully.

#+begin_src emacs-lisp

  (use-package vterm
    :commands vterm
    :config
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *")  ;; Set this to match your custom shell prompt
    ;;(setq vterm-shell "zsh")                       ;; Set this to customize the shell to launch
    (setq vterm-max-scrollback 10000))

#+end_src

** shell-mode

[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Interactive-Shell.html#Interactive-Shell][shell-mode]] is a middle ground between =term-mode= and Eshell.  It is *not* a terminal emulator so more complex terminal programs will not run inside of it.  It does have much better integration with Emacs because all command input in this mode is handled by Emacs and then sent to the underlying shell once you press Enter.  This means that you can use =evil-mode='s editing motions on the command line, unlike in the terminal emulator modes above.

*Useful key bindings:*

- =C-c C-p= / =C-c C-n= - go back and forward in the buffer's prompts (also =[[= and =]]= with evil-mode)
- =M-p= / =M-n= - go back and forward in the input history
- =C-c C-u= - delete the current input string backwards up to the cursor
- =counsel-shell-history= - A searchable history of commands typed into the shell

One advantage of =shell-mode= on Windows is that it's the only way to run =cmd.exe=, PowerShell, Git Bash, etc from within Emacs.  Here's an example of how you would set up =shell-mode= to run PowerShell on Windows:

#+begin_src emacs-lisp

  (when (eq system-type 'windows-nt)
    (setq explicit-shell-file-name "powershell.exe")
    (setq explicit-powershell.exe-args '()))

#+end_src

** Eshell

[[https://www.gnu.org/software/emacs/manual/html_mono/eshell.html#Contributors-to-Eshell][Eshell]] is Emacs' own shell implementation written in Emacs Lisp.  It provides you with a cross-platform implementation (even on Windows!) of the common GNU utilities you would find on Linux and macOS (=ls=, =rm=, =mv=, =grep=, etc).  It also allows you to call Emacs Lisp functions directly from the shell and you can even set up aliases (like aliasing =vim= to =find-file=).  Eshell is also an Emacs Lisp REPL which allows you to evaluate full expressions at the shell.

The downsides to Eshell are that it can be harder to configure than other packages due to the particularity of where you need to set some options for them to go into effect, the lack of shell completions (by default) for some useful things like Git commands, and that REPL programs sometimes don't work as well.  However, many of these limitations can be dealt with by good configuration and installing external packages, so don't let that discourage you from trying it!

*Useful key bindings:*

- =C-c C-p= / =C-c C-n= - go back and forward in the buffer's prompts (also =[[= and =]]= with evil-mode)
- =M-p= / =M-n= - go back and forward in the input history
- =C-c C-u= - delete the current input string backwards up to the cursor
- =counsel-esh-history= - A searchable history of commands typed into Eshell

We will be covering Eshell more in future videos highlighting other things you can do with it.

For more thoughts on Eshell, check out these articles by Pierre Neidhardt:
- https://ambrevar.xyz/emacs-eshell/index.html
- https://ambrevar.xyz/emacs-eshell-versus-shell/index.html

#+begin_src emacs-lisp

  (defun efs/configure-eshell ()
    ;; Save command history when commands are entered
    (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

    ;; Truncate buffer for performance
    (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

    ;; Bind some useful keys for evil-mode
    (evil-define-key '(normal insert visual) eshell-mode-map (kbd "C-r") 'counsel-esh-history)
    (evil-define-key '(normal insert visual) eshell-mode-map (kbd "<home>") 'eshell-bol)
    (evil-normalize-keymaps)

    (setq eshell-history-size         10000
          eshell-buffer-maximum-lines 10000
          eshell-hist-ignoredups t
          eshell-scroll-to-bottom-on-input t))

  (use-package eshell-git-prompt
    :after eshell)

  (use-package eshell
    :hook (eshell-first-time-mode . efs/configure-eshell)
    :config

    (with-eval-after-load 'esh-opt
      (setq eshell-destroy-buffer-when-process-dies t)
      (setq eshell-visual-commands '("htop" "zsh" "vim")))

    (eshell-git-prompt-use-theme 'powerline))


#+end_src

* File Management

** Dired

Dired is a built-in file manager for Emacs that does some pretty amazing things!  Here are some key bindings you should try out:

*** Key Bindings
**** Navigation

     *Emacs* / *Evil*
- =n= / =j= - next line
- =p= / =k= - previous line
- =j= / =J= - jump to file in buffer
- =RET= - select file or directory
- =^= - go to parent directory
- =S-RET= / =g O= - Open file in "other" window
- =M-RET= - Show file in other window without focusing (previewing files)
- =g o= (=dired-view-file=) - Open file but in a "preview" mode, close with =q=
- =g= / =g r= Refresh the buffer with =revert-buffer= after changing configuration (and after filesystem changes!)

**** Marking files

- =m= - Marks a file
- =u= - Unmarks a file
- =U= - Unmarks all files in buffer
- =* t= / =t= - Inverts marked files in buffer
- =% m= - Mark files in buffer using regular expression
- =*= - Lots of other auto-marking functions
- =k= / =K= - "Kill" marked items (refresh buffer with =g= / =g r= to get them back)
- Many operations can be done on a single file if there are no active marks!

**** Copying and Renaming files

- =C= - Copy marked files (or if no files are marked, the current file)
- Copying single and multiple files
- =U= - Unmark all files in buffer
- =R= - Rename marked files, renaming multiple is a move!
- =% R= - Rename based on regular expression: =^test= , =old-\&=

*Power command*: =C-x C-q= (=dired-toggle-read-only=) - Makes all file names in the buffer editable directly to rename them!  Press =Z Z= to confirm renaming or =Z Q= to abort.

**** Deleting files

- =D= - Delete marked file
- =d= - Mark file for deletion
- =x= - Execute deletion for marks
- =delete-by-moving-to-trash= - Move to trash instead of deleting permanently

**** Creating and extracting archives

- =Z= - Compress or uncompress a file or folder to (=.tar.gz=)
- =c= - Compress selection to a specific file
- =dired-compress-files-alist= - Bind compression commands to file extension

**** Other common operations

- =T= - Touch (change timestamp)
- =M= - Change file mode
- =O= - Change file owner
- =G= - Change file group
- =S= - Create a symbolic link to this file
- =L= - Load an Emacs Lisp file into Emacs

*** Configuration

#+begin_src emacs-lisp
  (use-package dired
    :ensure nil
    :commands (dired dired-jump)
    :bind (("C-x C-j" . dired-jump))
    :custom ((dired-listing-switches "-agho --group-directories-first"))
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "h" 'dired-single-up-directory
      "l" 'dired-single-buffer))
  
  (use-package dired-single
    :commands (dired dired-jump))
  
  (use-package all-the-icons-dired
    :hook (dired-mode . all-the-icons-dired-mode))
  
  (use-package dired-open
    :commands (dired dired-jump)
    :config
    ;; Doesn't work as expected!
    ;;(add-to-list 'dired-open-functions #'dired-open-xdg t)
    (setq dired-open-extensions '(("png" . "feh")
				  ("mkv" . "mpv"))))
  
  (use-package dired-hide-dotfiles
    :hook (dired-mode . dired-hide-dotfiles-mode)
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "H" 'dired-hide-dotfiles-mode))
  
  ;; (use-package dired-details) 
  
  (use-package dired-rainbow
    :defer 2
    :config
    (dired-rainbow-define-chmod directory "#6cb2eb" "d.*")
    (dired-rainbow-define html "#eb5286" ("css" "less" "sass" "scss" "htm" "html" "jhtm" "mht" "eml" "mustache" "xhtml"))
    (dired-rainbow-define xml "#f2d024" ("xml" "xsd" "xsl" "xslt" "wsdl" "bib" "json" "msg" "pgn" "rss" "yaml" "yml" "rdata"))
    (dired-rainbow-define document "#9561e2" ("docm" "doc" "docx" "odb" "odt" "pdb" "pdf" "ps" "rtf" "djvu" "epub" "odp" "ppt" "pptx"))
    (dired-rainbow-define markdown "#ffed4a" ("org" "etx" "info" "markdown" "md" "mkd" "nfo" "pod" "rst" "tex" "textfile" "txt"))
    (dired-rainbow-define database "#6574cd" ("xlsx" "xls" "csv" "accdb" "db" "mdb" "sqlite" "nc"))
    (dired-rainbow-define media "#de751f" ("mp3" "mp4" "mkv" "MP3" "MP4" "avi" "mpeg" "mpg" "flv" "ogg" "mov" "mid" "midi" "wav" "aiff" "flac"))
    (dired-rainbow-define image "#f66d9b" ("tiff" "tif" "cdr" "gif" "ico" "jpeg" "jpg" "png" "psd" "eps" "svg"))
    (dired-rainbow-define log "#c17d11" ("log"))
    (dired-rainbow-define shell "#f6993f" ("awk" "bash" "bat" "sed" "sh" "zsh" "vim"))
    (dired-rainbow-define interpreted "#38c172" ("py" "ipynb" "rb" "pl" "t" "msql" "mysql" "pgsql" "sql" "r" "clj" "cljs" "scala" "js"))
    (dired-rainbow-define compiled "#4dc0b5" ("asm" "cl" "lisp" "el" "c" "h" "c++" "h++" "hpp" "hxx" "m" "cc" "cs" "cp" "cpp" "go" "f" "for" "ftn" "f90" "f95" "f03" "f08" "s" "rs" "hi" "hs" "pyc" ".java"))
    (dired-rainbow-define executable "#8cc4ff" ("exe" "msi"))
    (dired-rainbow-define compressed "#51d88a" ("7z" "zip" "bz2" "tgz" "txz" "gz" "xz" "z" "Z" "jar" "war" "ear" "rar" "sar" "xpi" "apk" "xz" "tar"))
    (dired-rainbow-define packaged "#faad63" ("deb" "rpm" "apk" "jad" "jar" "cab" "pak" "pk3" "vdf" "vpk" "bsp"))
    (dired-rainbow-define encrypted "#ffed4a" ("gpg" "pgp" "asc" "bfe" "enc" "signature" "sig" "p12" "pem"))
    (dired-rainbow-define fonts "#6cb2eb" ("afm" "fon" "fnt" "pfb" "pfm" "ttf" "otf"))
    (dired-rainbow-define partition "#e3342f" ("dmg" "iso" "bin" "nrg" "qcow" "toast" "vcd" "vmdk" "bak"))
    (dired-rainbow-define vc "#0074d9" ("git" "gitignore" "gitattributes" "gitmodules"))
    (dired-rainbow-define-chmod executable-unix "#38c172" "-.*x.*"))
  
  (use-package dired-single
    :defer t)
  
  (use-package dired-ranger
    :defer t)
  
  (use-package dired-collapse
    :defer t)
  
  (evil-collection-define-key 'normal 'dired-mode-map
    "h" 'dired-single-up-directory
    "H" 'dired-omit-mode
    "l" 'dired-single-buffer
    "y" 'dired-ranger-copy
    "X" 'dired-ranger-move
    "p" 'dired-ranger-paste)
  
#+end_src

#+RESULTS:

* Runtime Performance

Dial the GC threshold back down so that garbage collection happens more frequently but in less time.

#+begin_src emacs-lisp

  ;; Make gc pauses faster by decreasing the threshold.
  (setq gc-cons-threshold (* 2 1000 1000))

#+end_src

* Navigation
** Ace-link
 :LOGBOOK:
 - State "DONE"       from "NEXT"       [2021-04-03 Sat 15:32]
 :END:
 Ace-link provides easy of navigation inside emacs self-hyperlinks or ad-hoc ones.
 #+begin_src emacs-lisp
   (use-package ace-link)
   (ace-link-setup-default)

   (define-key org-mode-map (kbd "ö") 'ace-link-org)
 #+end_src

 #+RESULTS:
 : ace-link-org

 - ö = (AltGr-p)




 # ** Keybinds
 # Change ISO_Level3_Shift for <f2> <=> 96  F12
 # Change 134 Super_R for Meta

 # keycode 133 = Super_L NoSymbol Super_L => Emacs's Meta

 # 108 ISO_Level3_Shift
 # 134 Super_R
 # 135 Super_R
 # 105 Control_R
 # 62  Shift_R
 # keycode 108 = ISO_Level3_Shift NoSymbol ISO_Level3_Shift
 # keycode 134 = Super_R NoSymbol Super_R
 # keycode 135 = Super_R NoSymbol Super_R

*** Fs
67  F1
68  F2
69  F3
70  F4
71  F5
72  F6
73  F7
74  F8
75  F9
76  F10
95  F11
96  F12

* Animated images (gif)
#+begin_src emacs-lisp
  ;; Copyright (C) 2014 Matus Goljer <matus.goljer@gmail.com>
  ;; Package-requires: ((dash "2.5.0"))
  (defun org-inline-image--get-current-image ()
    "Return the overlay associated with the image under point."
    (car (--select (eq (overlay-get it 'org-image-overlay) t) (overlays-at (point)))))
  
  (defun org-inline-image--get (prop)
    "Return the value of property PROP for image under point."
    (let ((image (org-inline-image--get-current-image)))
      (when image
        (overlay-get image prop))))
  
  (defun org-inline-image-animate ()
    "Animate the image if it's possible."
    (interactive)
    (let ((image-props (org-inline-image--get 'display)))
      (when (image-multi-frame-p image-props)
        (image-animate image-props))))
  
  (defun org-inline-image-animate-auto ()
    (interactive)
    (when (eq 'org-mode major-mode)
      (while-no-input 
        (run-with-idle-timer 0.3 nil 'org-inline-image-animate))))
  
  (setq org-inline-image--get-current-image (byte-compile 'org-inline-image--get-current-image))
  (setq org-inline-image-animate  (byte-compile 'org-inline-image-animate ))
  (add-hook 'post-command-hook 'org-inline-image-animate-auto)
#+end_src
* Presentation setup
#+begin_src emacs-lisp
(use-package org-present)
#+end_src

#+RESULTS:

* Prerequisites 
#+begin_src emacs-lisp :tangle yes
  (use-package ein)
  (use-package esxml)
  (use-package prescient)
  (use-package company-prescient)
  (use-package xelb)
  (use-package cider)
#+end_src

#+RESULTS:

* Some general requirements left
#+begin_src emacs-lisp
  ;;  (use-package versuri)
  (use-package esxml)
  (use-package prescient)
  (use-package company-prescient)
  (use-package xelb)
  (use-package cider)
#+end_src

#+RESULTS:
: t

* Scratch Buffer
  #+begin_src emacs-lisp
(defun my-scratch-buffer ()
"Create a new scratch buffer -- \*hello-world\*"
(interactive)
  (let ((n 0)
        bufname buffer)
    (catch 'done
      (while t
        (setq bufname (concat "*hello-world"
          (if (= n 0) "" (int-to-string n))
            "*"))
        (setq n (1+ n))
        (when (not (get-buffer bufname))
          (setq buffer (get-buffer-create bufname))
          (with-current-buffer buffer
            (org-mode))
          ;; When called non-interactively, the `t` targets the other window (if it exists).
          (throw 'done (display-buffer buffer t))) ))))
  #+end_src

  #+RESULTS:
  : my-scratch-buffer

* Font Icons
=M-x all-the-icons-install-fonts=
#+begin_src emacs-lisp
#+end_src

* Periodic Tables
  #+begin_src emacs-lisp
    (use-package chembalance)
    (use-package chemtable)
  #+end_src
 
* Calendar Calfw
#+begin_src emacs-lisp
  (use-package calfw-org)
  (use-package calfw-cal)
  (use-package calfw-ical)
  (use-package calfw-gcal)
#+end_src

#+RESULTS:

* Reveal.js presentations
pt-br: 

#+begin_src emacs-lisp
  (use-package ox-reveal)
#+end_src

#+RESULTS:

#+begin_src emacs-lisp
  (use-package htmlize)
#+end_src

#+RESULTS:
 
* Emacs extension by shell scripting

#+begin_src emacs-lisp
  (defun tidy-html ()
    "Tidies the HTML content in the buffer using `tidy'"
    (interactive)
    (shell-command-on-region
     ;; beginning and end of buffer
     (point-min)
     (point-max)
     ;; command and parameters
     "tidy -i -w 120 -q"
     ;; output buffer
     (current-buffer)
     ;; replace?
     t
     ;; name of the error buffer
     "*Tidy Error Buffer*"
     ;; show error buffer?
     t))
#+end_src

#+RESULTS:
: tidy-html

* Celestial-mode-line
#+begin_src emacs-lisp
  (use-package celestial-mode-line
    :config
    (setq calendar-longitude "20.54S")
    (setq calendar-latitude "47.40W")
    (setq calendar-location-name "Franca, SP")
    (setq global-mode-string '("" celestial-mode-line-string display-time-string))
    (defvar celestial-mode-line-phase-representation-alist '((0 . "○") (1 . "☽") (2 . "●") (3 . "☾")))
    (defvar celestial-mode-line-sunrise-sunset-alist '((sunrise . "☀↑ ") (sunset . "☀↓ ")))
    (defvar celestial-mode-line-phase-representation-alist '((0 . "( )") (1 . "|)") (2 . "(o)") (3 . "|)")))
    (defvar celestial-mode-line-sunrise-sunset-alist '((sunrise . "*^") (sunset . "*v")))
    (celestial-mode-line-start-timer)
    :init
    (define-key global-map
      (kbd "µ")
      (display-message-or-buffer (message "`%s'" (eval '(solar-sunrise-sunset-string (calendar-current-date)))))))
#+end_src

#+RESULTS:
: t

#+begin_src emacs-lisp :tangle no
(eval '(solar-sunrise-sunset-string (calendar-current-date)))
#+end_src

#+RESULTS:
: Sunrise 3:55am (-03), sunset 8:37pm (-03) at Franca, SP (16:42 hrs daylight)

** Bindings for retriving data
#+begin_src emacs-lisp :tangle no
#+end_src

#+RESULTS:
: ‘Sunrise 3:55am (-03), sunset 8:37pm (-03) at Franca, SP (16:42 hrs daylight)’

#+begin_src emacs-lisp
(message "hello")
#+end_src

#+RESULTS:
: hello

‘Sunrise 3:55am (-03), sunset 8:37pm (-03) at Franca, SP (16:42 hrs daylight)’

* Load Desktop.el and other auxiliaries

#+begin_src emacs-lisp
(use-package load-relative)
#+end_src

#+RESULTS:

#+begin_src emacs-lisp
  (load-relative "./pl.el")
  (load-relative "./editing.el")
  (load-relative "./desktop.el")
#+end_src

#+RESULTS:
: t

