((magit-branch nil)
 (magit-commit nil)
 (magit-dispatch nil)
 (magit-gitignore nil)
 (magit-merge nil
	      ("--strategy=ours"))
 (magit-merge:--strategy "ours")
 (magit-pull nil)
 (magit-push nil)
 (magit-stash nil))
