;; -*- emacs-lisp -*- <21/10/26 08:31:12 /home/buddhilw/.emacs.default/var/tramp/persistency.el>
;; Tramp connection history.  Don't change this file.
;; Run `M-x tramp-cleanup-all-connections' instead.

(((tramp-file-name "sudo" "root" nil "localhost" nil nil nil)
  ("uname" "Linux 5.12.10-artix1-1")
  ("locale" "LC_ALL=en_US.utf8")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/sbin" "/usr/sbin" "/usr/local/bin" "/usr/local/sbin"))
  ("pipe-buf" 4096)
  ("remote-shell" "/bin/sh")
  ("readlink" "\\readlink")
  ("stat" "env QUOTING_STYLE=locale \\stat")
  ("file-exists" "test -e")
  ("case-insensitive" nil)
  ("perl-file-spec" t)
  ("perl-cwd-realpath" t)
  ("perl" "\\perl")
  ("bzr" nil)
  ("git" "\\git")
  ("hg" nil)
  ("id" "/bin/id")
  ("gid-integer" 0)
  ("gid-string" "root")
  ("uid-integer" 0)
  ("~root" "/root"))
 ((tramp-file-name "sudo" "root" nil "re-lapse" nil nil nil)
  ("uname" "Linux 5.13.12-artix1-1")
  ("locale" "LC_ALL=en_US.utf8")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/sbin" "/usr/sbin" "/usr/local/bin" "/usr/local/sbin"))
  ("pipe-buf" 4096)
  ("remote-shell" "/bin/sh")
  ("file-exists" "test -e")
  ("stat" "env QUOTING_STYLE=locale \\stat")
  ("id" "/bin/id")
  ("uid-integer" 0)
  ("gid-integer" 0)
  ("gid-string" "root")
  ("readlink" "\\readlink"))
 ((tramp-file-name "sudo" "root" nil "relapse" nil nil nil)
  ("uname" "Linux 5.13.12-artix1-1")
  ("locale" "LC_ALL=en_US.utf8")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/sbin" "/usr/sbin" "/usr/local/bin" "/usr/local/sbin"))
  ("pipe-buf" 4096)
  ("remote-shell" "/bin/sh")
  ("file-exists" "test -e")
  ("stat" "env QUOTING_STYLE=locale \\stat")
  ("id" "/bin/id")
  ("uid-integer" 0)
  ("gid-integer" 0)
  ("gid-string" "root")
  ("readlink" "\\readlink"))
 ((tramp-file-name "sudo" "root" nil "laptop" nil nil nil)
  ("uname" "Linux 5.14.14-artix1-1")
  ("locale" "LC_ALL=en_US.utf8")
  ("test" "test")
  ("remote-path"
   ("/bin" "/usr/bin" "/sbin" "/usr/sbin" "/usr/local/bin" "/usr/local/sbin"))
  ("pipe-buf" 4096)
  ("remote-shell" "/bin/sh")
  ("file-exists" "test -e")
  ("stat" "env QUOTING_STYLE=locale \\stat")
  ("id" "/bin/id")
  ("uid-integer" 0)
  ("gid-integer" 0)
  ("gid-string" "root")
  ("readlink" "\\readlink")))
